FROM ubuntu
LABEL maintainer="PedroVaca"
RUN apt update 
RUN apt install curl --yes 
RUN apt install vim --yes
RUN apt update && apt install net-tools -y
RUN apt-get clean
RUN rm -rf /var/lib/apt/lists/*
WORKDIR /app
WORKDIR /tools
WORKDIR /tools
COPY codigo.txt /app/